### ISSUE TITLE
Not Validated With ZATCA SDK

### ISSUE THREAD

**Issue by ahosainy** [aljbri/Zatca.Net#1]
Dear Aljbri ,

Great job thanks for your awesome solution , there was a small issue in the solution but after fixing it every thing went good

it was the ID fixed to 1 , the correction change it to be dynamic as the id parameter  
private byte[] getBytes(int id, byte[] Value)
        {
            byte[] val = new byte[2 + Value.Length];
            val[0] = (byte)id;
            val[1] = (byte)Value.Length;
            Value.CopyTo(val, 2);
            return val;
        }

**Comment by aljbri** [comment]
Dear ahosainy,
The bug has been fixed.
thank you,
