### ISSUE TITLE
Additional Text on the Seller Name Appearing

### ISSUE THREAD

**Issue by apdeguzman03** [aljbri/Zatca.Net#2]
There is a n Additional Character Added Infron of the Sellers Name once Decoded. One information the Seller Name im using is quite long.

Thanks

**Comment by aljbri** [comment]
could you provide an example of that problem?

**Comment by apdeguzman03** [comment]
Hi aljbri,
I was able to discern that its not a bug. Since it needs to be decoded manually.Thanks for this source code.
