### ISSUE TITLE
Scanning with zatca Vat mob application not working

### ISSUE THREAD

**Issue by lisaShahid** [aljbri/Zatca.Net#4]
Hi @aljbri, 
First of all thanks for the code.
While scanning with the zatca vat moblie application, data is not showing if the vat no is registered with zatca, otherwise it is showing.is this an issue with the code or error from my side?
In some third party application, it is working fine
Thanks in advance.

**Comment by T-Alkathiri** [comment]
I am facing same problem.
Thank you very much.

**Comment by aljbri** [comment]
is this the application [com.zatca.vat](https://play.google.com/store/apps/details?id=com.zatca.vat) that you were using?
could you please confirm that?

**Comment by aljbri** [comment]
@lisaShahid : Is this the application [com.zatca.vat](https://play.google.com/store/apps/details?id=com.zatca.vat) that you were using? could you please confirm that?

**Comment by lisaShahid** [comment]
> @lisaShahid : Is this the application [com.zatca.vat](https://play.google.com/store/apps/details?id=com.zatca.vat) that you were using? could you please confirm that?

Yes.. But when i changed the date format its working now.. thanks a lot for your code.   Jazāk Allāhu Khayran

**Comment by aljbri** [comment]
> > @lisaShahid : Is this the application [com.zatca.vat](https://play.google.com/store/apps/details?id=com.zatca.vat) that you were using? could you please confirm that?
> 
> Yes.. But when i changed the date format its working now.. thanks a lot for your code. Jazāk Allāhu Khayran

what is the date format that works?  to make it the default date format of the output code.

**Comment by lisaShahid** [comment]
> > > @lisaShahid : Is this the application [com.zatca.vat](https://play.google.com/store/apps/details?id=com.zatca.vat) that you were using? could you please confirm that?
> > 
> > 
> > Yes.. But when i changed the date format its working now.. thanks a lot for your code. Jazāk Allāhu Khayran
> 
> what is the date format that works? to make it the default date format of the output code.

```
public TLVCls(String Seller, String TaxNo, DateTime dateTime, Double Total, Double Tax)
        {
            this.Seller = Encoding.UTF8.GetBytes(Seller);
            this.VatNo = Encoding.UTF8.GetBytes(TaxNo);

           **// this.dateTime = Encoding.UTF8.GetBytes(dateTime.ToString());
        this.dateTime = Encoding.UTF8.GetBytes(dateTime.ToString("yyyy-MM-dd HH:mm:ss"));**  //this i changed

            this.Total = Encoding.UTF8.GetBytes(Total.ToString());
            this.Tax = Encoding.UTF8.GetBytes(Tax.ToString());
        }

```

**Comment by T-Alkathiri** [comment]
> > > > @lisaShahid : Is this the application [com.zatca.vat](https://play.google.com/store/apps/details?id=com.zatca.vat) that you were using? could you please confirm that?
> > > 
> > > 
> > > Yes.. But when i changed the date format its working now.. thanks a lot for your code. Jazāk Allāhu Khayran
> > 
> > 
> > what is the date format that works? to make it the default date format of the output code.
> 
> ```
> public TLVCls(String Seller, String TaxNo, DateTime dateTime, Double Total, Double Tax)
>         {
>             this.Seller = Encoding.UTF8.GetBytes(Seller);
>             this.VatNo = Encoding.UTF8.GetBytes(TaxNo);
> 
>            **// this.dateTime = Encoding.UTF8.GetBytes(dateTime.ToString());
>         this.dateTime = Encoding.UTF8.GetBytes(dateTime.ToString("yyyy-MM-dd HH:mm:ss"));**  //this i changed
> 
>             this.Total = Encoding.UTF8.GetBytes(Total.ToString());
>             this.Tax = Encoding.UTF8.GetBytes(Tax.ToString());
>         }
> ```

Thank you very much for sharing.

**Comment by aljbri** [comment]
> > > > @lisaShahid : Is this the application [com.zatca.vat](https://play.google.com/store/apps/details?id=com.zatca.vat) that you were using? could you please confirm that?
> > > 
> > > 
> > > Yes.. But when i changed the date format its working now.. thanks a lot for your code. Jazāk Allāhu Khayran
> > 
> > 
> > what is the date format that works? to make it the default date format of the output code.
> 
> ```
> public TLVCls(String Seller, String TaxNo, DateTime dateTime, Double Total, Double Tax)
>         {
>             this.Seller = Encoding.UTF8.GetBytes(Seller);
>             this.VatNo = Encoding.UTF8.GetBytes(TaxNo);
> 
>            **// this.dateTime = Encoding.UTF8.GetBytes(dateTime.ToString());
>         this.dateTime = Encoding.UTF8.GetBytes(dateTime.ToString("yyyy-MM-dd HH:mm:ss"));**  //this i changed
> 
>             this.Total = Encoding.UTF8.GetBytes(Total.ToString());
>             this.Tax = Encoding.UTF8.GetBytes(Tax.ToString());
>         }
> ```

Thank you
