### ISSUE TITLE
Zatca 2nd Phase

### ISSUE THREAD

**Issue by OmarHarbi** [aljbri/Zatca.Net#6]
Eng.Abdul Salam
Thank you for your great effort in providing this library and I have really benefited from it in my program.

Please help us provide 2nd Phase

**Comment by T-Alkathiri** [comment]
Please Eng.Abdul Salam Help us in this case
Your help will be highly appreciated.
Thank you very much.

**Comment by aljbri** [comment]
Due to my busy schedule, I will try my best to do it before the died line and I appreciate your feedback...

**Comment by T-Alkathiri** [comment]
> Due to my busy schedule, I will try my best to do it before the died line and I appreciate your feedback...

Thank you sooooooooooo much.
God bless you جزاك الله كل خير

**Comment by Harisul44** [comment]
Thank you so much. We hope that you will complete zatca 2nd as soon as.
Best of luck.

**Comment by OmarHarbi** [comment]
الله يبيض وجهك وفعلا حنا محتاجينها
